blank_issues_enabled: false
contact_links:
  - name: "\U0001F6A8 Security issue"
    about: Report a security issue.
    url:  https://ckeditor.com/contact/
  - name: "\U0001F4F1 Licensed Customers support"
    about: Support channel for Licensed Customers.
    url: https://support.ckeditor.com/hc/en-us/requests/new
